create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    email text not null,
    birth_date date null,
    passage_user_id text not null,
    zodiac_sign text null,
    last_cycle_start date null,
    last_cycle_length bigint null,
    constraint users_pkey primary key (passage_user_id),
    constraint users_passage_user_id_key unique (passage_user_id)
  ) tablespace pg_default;

create table
  public.entries (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    date date not null,
    flow text not null,
    mood text null,
    craving text null,
    symptom text null,
    user_id text not null,
    constraint entries_pkey primary key (id),
    constraint entries_user_id_fkey foreign key (user_id) references users (passage_user_id)
  ) tablespace pg_default;

create table
  public.horoscopes (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    zodiac_sign text not null,
    date date not null,
    description text not null,
    constraint horoscopes_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.insights (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id text not null,
    date date not null,
    description text not null,
    constraint insights_pkey primary key (id),
    constraint insights_user_id_fkey foreign key (user_id) references users (passage_user_id)
  ) tablespace pg_default;

